language: C
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libtool
    - libglib2.0-dev
    - libmagic-dev
    - libxml2-dev
    - libmicrohttpd-dev
    - libcurl4-openssl-dev
    - libjansson-dev
    - libjansson4
    - autoconf-archive
  coverity_scan:
    project:
      name: armadito/armadito-av
      description: Build submitted via Travis CI
    notification_email: vhamon@teclib.com
    build_command_prepend: "./configure; make clean"
    build_command: make -j 4
    branch_pattern: coverity_scan
  sonarqube:
    branches:
    - DEV

deploy:
  skip_cleanup: true
  provider: launchpad
  slug: "~armadito/armadito-av/+git/main"
  oauth_token:
    secure: OS2HDzbkmQVyugXPCO8qinEwWOTn7zu5VfhbwvcOuOEfBmYZ7xPagTxEdatEBGto20YN+bbGU0zFJLCZMrTyHCXr8WnhFFE7DDGvAGhymJ/XUkZriUVp+O815GT2+NmfER11v8+jdtfm9DkIft0wSBcmq7/bNKRxaVSJ0/NZdODc1uHp2PIVnRhnlkxe+971183JGduv148+Tnt+gFGd7BgjknMZRee+XDS/VXFa1Qi0FBRZj2IKxD0kZV6oUMrVGOfd7ea/uaVPsqjmYs2w4v1yL4FsZE42Vfxc+lne5aR2gxQ29yb6GtkGuGm8LH1W49+MYy9F1m3jDM3KxKF0/EW6Ra6uFQq88gIt5MjyXkIom53kPUVNGOFsTrEREU1W4mjY9ljvEdV62/Bpdt6mpXbWT0P0gRTejL2r1t0L0oTBOkaxPXxcPiIR0HmLx/UbXDaya56NEDqGVEr4LwfwVg6ZpreW4Rxo1wa9fy2FcHQX0BePW3XShR26vPhtjzG8zOLcS0rEG7paUol5nF8CPE1skmh2e6bxLQmHRjP+hSZViWa/JZtz6CC1oBVu02KBdYkR4TkK+MdkxX6XTo7/M+HGBTum6MlZmgs6r/crLjBJdhXWT19PgB4/WDqQOa43DLexLSb24m07HH7eD+hsXsDx+HpurFm2p818IhVdCws=
  oauth_token_secret:
    secure: PxwcHUPW5gId13eGHqkghqfnSnhpySWdnE6AGE1pTJgoiaetXI90zNr9OcAU2yC2MgQ5egACXWQW6U17zjYwxmcxFyiZO1KMB+877TB3YfGwTRZCwP/HSQxWckBpkrKt9W293OBfKkrd48l6cqPfo4mexhnBpbZ+NvLRFtrEqn+fHa/6e7XtSvqV97KaTVvKFTtRkvmGog+Hc3d4hdEGD4+AeR8YL3bKvbIhBJL3MzFu6POMRguD3247WWDVUNgoYwwxq0UmoVUcYTUXUB/A07iz0+PT51T9A9iOZEajqS+fZmEM7CsmLBs0K7VuvBekxQLmi+9XHndeK66vr576VPMqBL2wl592Ud+rIY6pRGAu8e0HxsyAPdK4zjXfATy/SntEURT/W6cjw9RwMakFZT8FVuFCF5oWyLhkV6UrECEkVmx7qDG2EcmWbcBeQ0y1yV8oBZec21sUN0X1lT+v9kdgf3KYAqhLz8JrhqxHIhjrEAwSZ5ShS4LJwqnmwY8f6sD9OjCvuaSdgOo4qyOQ0yHivdyi1L/IvOQXW4OTPf8RPtog2OYiCN0Fv1VfbAH8V7KhM2WFqg4rPTU9zT2IbZbkx6SL3HbvdRA+AicTULbxjbZmObR9SG6avjS0tSzpycFkhXgG+qPyUQSVPO30cNyh+LSTTMxe0hc2UPTQEXA=
  on:
    branch: release

env:
  global:
  - secure: VoHY4zThCD1+/AaAMi5dAU6lS9EA8jUo2Bi0t0WExTf6CJfR9sbLi5A6wizfsiJOuPSTrgoSooJ+HeKj4s9nk8+UYOXDaWMCnBj4iWwepcp7f4DxWvlYiItjaoO7c7/8gzd/8Fx9iSoy8k5ZD5sTdp34qJrrYs08y5lcSq+GZLKQP5Wfbe24Js1Z8zqVjDoPgC6vEf2ntrJzBoV81g5oofReSVYQL5+UcRvxmAZm2nqzFsyk/QFlVaeLA/J6qQfINZOMJaXpvpEdBdb1XnBZbHt3wXNrSQbUKf4qvVvKcA2zg0I2+1P222DrpC82Ogqz1I7tgm2f37GrEn7sqCtO+3N4rqEdMPScn41W0/i49xigKMvGPxEzMqSVYNF171KIV+qqBlm7bGXPvJHLuctAqxnwSYzr4k+tahn2ZVt7IRtHw64tE+W8OJzU+RLK1rWaGZ4z7MSxvnqlURn6X0SzMI8V4/pE2bFSOpd7srlnu6+bncrN22BYQYc/X9IYaa+4esRI9PlTimE7Dcp+Au8ovZa5JQyORUjl414zRMdJtglmropxdKY1+nBhzNh10/jbGKtUMizG1PUPlPWSODwJHRXVEyI72SMtYn/OjNUgzhw2yE8kfYt5hE3CN9racS1TkzafIo2BLsxHEFnUBuI6G1uwwNfu1sjDEAvjfwHYlFo=
  - secure: jaoDidvyYDmX1DuapIbRpQDVW0oKz/qHuW7zvRVkDSuZ76sFv+TDh8J1GoqfIVcI9wZfoMYv0xHfTR66tKVGXkA7x+8cn94pqcNo8FP2UASKQnXNgYJ01SapU9Kp/g+QddxrGOjmrs6WnS1Je0RyjHUWomfrMxVQMYfHIWwS8sYUsQDydkQHy63iokLIjFs8Vp5BkSj/ZIHw86DHaqkvPTSIPb60fcuL3rR+/pnYTgxGGICIZr3Ga64p7V4pbFFOhY5f0meUzBMX4iqZMWO7Z09scYkHph9/741tbfwQSI7vd/1eSbhHXaaXMEIeWBHjHfo2m0Ihfp3xolEyE/NnXbv3UK99Hl1o/GRlb+m2WRD1xF+XNg3lBsXiMZV2nGiDz2fEjc+KrGfUHinLk1CXAkOrBeDHfeeu/zolDIv50HRpG8vWXe3ls8kvi4k+Yn5hlIFRCow6ejZcBIC50HFXiEYYm581rhamPK/rHUzUGEdr1m2ZktODSoj1uXLZ+r0xYHcXMvROdE5tGsbwacQ0WmoeLIQRW3Im0uYiXh0ncc1LdVyg4ing++L45g6XfdhZJiw16ZRGWad2Pc/+HyaDsyKSPv/I80DIF6C0U5B/rINN5shmVMo8LvrVus9S3ILF3sezrurAE9342BGxVF03p2rhOwYrp6LFmvW42zczW38=

before_install:
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END
  CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
- wget https://sonarqube.com/static/cpp/build-wrapper-linux-x86.zip
- unzip build-wrapper-linux-x86.zip
- export PATH=$PWD/build-wrapper-linux-x86:$PATH

compiler:
- gcc

before_script:
- "./autogen.sh"

script:
- "./configure"
- build-wrapper-linux-x86-64 --out-dir build-wrapper-out make clean all
- sonar-scanner -X -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
