language: C
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libtool
    - libglib2.0-dev
    - libmagic-dev
    - libxml2-dev
    - libmicrohttpd-dev
    - libcurl4-openssl-dev
    - libjansson-dev
    - libjansson4
    - autoconf-archive
  coverity_scan:
    project:
      name: armadito/armadito-av
      description: Build submitted via Travis CI
    notification_email: vhamon@teclib.com
    build_command_prepend: "./configure; make clean"
    build_command: make -j 4
    branch_pattern: coverity_scan
  sonarqube:
    branches:
    - DEV
deploy:
  skip_cleanup: true
  provider: launchpad
  slug: "~armadito/armadito-av/+git/main"
  oauth_token:
    secure: lhh4B51SuX/IYKecq+rGS0B3Xm1U1BNMfMYs0dLEZE4xNlEGLCRXvGCkoL6UuKZSdwtZVBryQGk251zCY1UhHZPqFF84zcl4dkz6L3xzX6SSncnp6nyPBszIgjMtUB9Ycr9JNv8iiXcABpoiiadmDYDHHa5k4SvOPUybry4TWKHaOZmLi1/S0NvGSmGcLEfd7ErF+D4lxgLbDc5NxkYr4NLo/+R1BzbZQEZ/P3YhbZkRwoVCn80tIo2wuAbsxxUr7uMG9Q24zKNxnryvRzCzw/snYRkIYYn9/9upv9Fqa7QOEBO8a1ESOATjSP8xWPfffqV8GVRJj5QZ/NQymIwLMCusSXhh0kMGl+DG5ewSsN/+l8qA+boK91kDlQy5HRhNsrORT5vhQAUDThIysY3V1PGWzx8L5B8cfY57qHZXEDUOZsx6p+f8nOEYgzsxGPIeSgnnhGgBaYtxcAGiwwrY/tnaazH+xlN2zB2Zr8jnAT6CZ5xugfDeydbYDMB+sw890DshJCZMkawLgx7p5YhnWvTxSsnDKT3xy705uH/FBm5YG3kkGwKDgWVqpmkz3R0bnlqumiWlZpltnAKPYKu/NHzQU1iezoJUfxUV75U5RHOhXT3pl1qVRFSV7XW21sYGcAAklbzu3/njNJwoDYTY9RwSHlnabqovfZ0qJkyBY6c=
  oauth_token_secret:
    secure: pXBuBZnFwh+k6U+9/e4c3bETS0xFUR1aJbawEWOobJJ5iT7ZN58ReJs3RMENvoDc3sA1laLdpT3B8mvHoJEO1kFvyZU6v2MwOZgJ1qWmtKVq1drnfAzrB7jrFqWHWA3eyDTBqwGveL8noPOcGDVQB8vrBwv4EnKDjYTai8U0Y/TUa+zMna7cvm0J+JJ4kdjR5w5/fFw7FXzz7KbUlSq0SCStUOZ2rSwh2+5wPgXb6WGVpfSQTkQ/taVPBMuHjaTEz7C/e6NLkjm29ZtaDVGO9dFTsS/jEO9FqN+5nAEoNp+GgcLXGQtqVXdf9wg81/umchWnXpCAzEE8BR5g8ndbpuqMe89XtK0VptI5QTY6QUWzV2vXNXCktdjc1TMRLYTiFegyKCG6UA5E+J0ULHqCh8kuJbOIvSnShxBfspjE5gm9uloOA5NdwYt082Wtcyxl7PMYS6IsN8LWAlIUYf98R2riOfTYaSWBWHRw+PB1JB4yClZNs91vEi08q6yO58Si9goMXTYwUTxpWLURWZAZrzVoyyDSMeeoNmE/8zrR7WRsfkfhtSe/zcRG/VZPSixHierLxfBlvArwUDR5l0iuqAtHgtIsfBCrhKYONGuhcWpJFV11Kp5R09dIr2M27v+TTSZhX+qBVqs2qpvGppYPmm0WV+/1r8yHf4DPvNmPpTo=
  on:
    branch: release
env:
  global:
  - secure: VoHY4zThCD1+/AaAMi5dAU6lS9EA8jUo2Bi0t0WExTf6CJfR9sbLi5A6wizfsiJOuPSTrgoSooJ+HeKj4s9nk8+UYOXDaWMCnBj4iWwepcp7f4DxWvlYiItjaoO7c7/8gzd/8Fx9iSoy8k5ZD5sTdp34qJrrYs08y5lcSq+GZLKQP5Wfbe24Js1Z8zqVjDoPgC6vEf2ntrJzBoV81g5oofReSVYQL5+UcRvxmAZm2nqzFsyk/QFlVaeLA/J6qQfINZOMJaXpvpEdBdb1XnBZbHt3wXNrSQbUKf4qvVvKcA2zg0I2+1P222DrpC82Ogqz1I7tgm2f37GrEn7sqCtO+3N4rqEdMPScn41W0/i49xigKMvGPxEzMqSVYNF171KIV+qqBlm7bGXPvJHLuctAqxnwSYzr4k+tahn2ZVt7IRtHw64tE+W8OJzU+RLK1rWaGZ4z7MSxvnqlURn6X0SzMI8V4/pE2bFSOpd7srlnu6+bncrN22BYQYc/X9IYaa+4esRI9PlTimE7Dcp+Au8ovZa5JQyORUjl414zRMdJtglmropxdKY1+nBhzNh10/jbGKtUMizG1PUPlPWSODwJHRXVEyI72SMtYn/OjNUgzhw2yE8kfYt5hE3CN9racS1TkzafIo2BLsxHEFnUBuI6G1uwwNfu1sjDEAvjfwHYlFo=
  - secure: jaoDidvyYDmX1DuapIbRpQDVW0oKz/qHuW7zvRVkDSuZ76sFv+TDh8J1GoqfIVcI9wZfoMYv0xHfTR66tKVGXkA7x+8cn94pqcNo8FP2UASKQnXNgYJ01SapU9Kp/g+QddxrGOjmrs6WnS1Je0RyjHUWomfrMxVQMYfHIWwS8sYUsQDydkQHy63iokLIjFs8Vp5BkSj/ZIHw86DHaqkvPTSIPb60fcuL3rR+/pnYTgxGGICIZr3Ga64p7V4pbFFOhY5f0meUzBMX4iqZMWO7Z09scYkHph9/741tbfwQSI7vd/1eSbhHXaaXMEIeWBHjHfo2m0Ihfp3xolEyE/NnXbv3UK99Hl1o/GRlb+m2WRD1xF+XNg3lBsXiMZV2nGiDz2fEjc+KrGfUHinLk1CXAkOrBeDHfeeu/zolDIv50HRpG8vWXe3ls8kvi4k+Yn5hlIFRCow6ejZcBIC50HFXiEYYm581rhamPK/rHUzUGEdr1m2ZktODSoj1uXLZ+r0xYHcXMvROdE5tGsbwacQ0WmoeLIQRW3Im0uYiXh0ncc1LdVyg4ing++L45g6XfdhZJiw16ZRGWad2Pc/+HyaDsyKSPv/I80DIF6C0U5B/rINN5shmVMo8LvrVus9S3ILF3sezrurAE9342BGxVF03p2rhOwYrp6LFmvW42zczW38=
before_install:
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END
  CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
- wget https://sonarqube.com/static/cpp/build-wrapper-linux-x86.zip
- unzip build-wrapper-linux-x86.zip
- export PATH=$PWD/build-wrapper-linux-x86:$PATH
compiler:
- gcc
before_script:
- "./autogen.sh"
script:
- "./configure"
- build-wrapper-linux-x86-64 --out-dir build-wrapper-out make clean all
- sonar-scanner -X -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
